// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezgenai.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezgenai.ModelManager;
import ezgenai.SearchParameterProxyHandler;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_EZGenAI_RetrieveSearchParameters extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private final java.lang.String model;

	public JA_EZGenAI_RetrieveSearchParameters(
		IContext context,
		java.lang.String _model
	)
	{
		super(context);
		this.model = _model;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return SearchParameterProxyHandler.importSearchParameters(getContext(), ModelManager.getModel(model).getDefaultGeneratorParams());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_EZGenAI_RetrieveSearchParameters";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
