// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezgenai.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezgenai.Prompter;
import ezgenai.SearchParameterProxyHandler;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_EZGenAI_Prompt extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String model;
	private final java.lang.String promptText;
	/** @deprecated use com.mendix.utils.ListUtils.map(searchParameters, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __searchParameters;
	private final java.util.List<ezgenai.proxies.SearchParameter> searchParameters;

	public JA_EZGenAI_Prompt(
		IContext context,
		java.lang.String _model,
		java.lang.String _promptText,
		java.util.List<IMendixObject> _searchParameters
	)
	{
		super(context);
		this.model = _model;
		this.promptText = _promptText;
		this.__searchParameters = _searchParameters;
		this.searchParameters = java.util.Optional.ofNullable(_searchParameters)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(searchParametersElement -> ezgenai.proxies.SearchParameter.initialize(getContext(), searchParametersElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Prompter.prompt(model, promptText, SearchParameterProxyHandler.exportSearchParameters(searchParameters));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_EZGenAI_Prompt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
